console.log("Date in JS")
let date = new Date()
console.log(date)
console.log(date.toString())
console.log(date.toDateString())
console.log(date.toISOString())
console.log(date.toJSON())
console.log(date.toLocaleDateString())
console.log(date.toLocaleString())
console.log(date.toLocaleTimeString())
console.log(date.toTimeString())
console.log(date.toUTCString())
console.log(date.getDate())
console.log(date.getDay())
console.log(date.getMonth())
console.log(date.getHours())
console.log(date.getMinutes())
console.log(date.getSeconds())
console.log(date.getMilliseconds())
console.log(date.getFullYear())

date.setDate(31)
date.setMonth(4)
date.setFullYear(1987)
console.log(date)

// Create Custom Date
console.log("Create Custom Date")
let newdate = new Date("2025-12-27T00:00:00")
console.log(newdate)
console.log((Date.now()))
console.log(date.toDateString())
console.log(date.toTimeString())
console.log(date.toISOString())

